# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textEdit', '0007_auto_20181127_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textEdit.Topic'),
        ),
    ]
